### ISSUE TITLE
file not generated: process_log/log.txt file

### ISSUE THREAD

**Issue by hshcao** [cruizperez/MicrobeAnnotator#10]
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/hcao/hshcao/megahitmG20/MicroAnnotator/process_log/log.txt'

**Comment by Jigyasa3** [comment]
Hey @cruizperez 

Sorry for opening the issue again! I am running into the same problem, where MicrobeAnnotator cannot find the log.txt file (coz its not generating it), but I don't understand the error message. 
I have successfully installed the database (--light version) and have the diamond binary file in PATH.

$`module load python/3.7.3`
$` /home/j/jigyasa-arora/.local/bin/microbeannotator -i refined-unnamed-272-97.bin.30.fa.faa -d ${DB_DIR} -o test/ -m diamond -p 1 -t 16 --light --refine --continue_run`

2021-08-20 15:18:15,792 [INFO]:  ---- This is MicrobeAnnotator v2.0.4 ----
2021-08-20 15:18:15,792 [INFO]: Validating user inputs
2021-08-20 15:18:15,793 [INFO]: Passed
2021-08-20 15:18:15,793 [INFO]: Processing 1 files. I will run 1 files in parallel with 16 threads per file.
2021-08-20 15:18:15,796 [INFO]: Restarting from last checkpoint
Traceback (most recent call last):
  File "/home/j/jigyasa-arora/.local/bin/microbeannotator", line 981, in <module>
    main()
  File "/home/j/jigyasa-arora/.local/bin/microbeannotator", line 299, in main
    with open(process_log_folder / "log.txt", 'r') as logfile:
FileNotFoundError: [Errno 2] No such file or directory: 'test/process_log/log.txt'


Any suggestion will be helpful!
