### ISSUE TITLE
DB build error on step 9

### ISSUE THREAD

**Issue by ryanjameskennedy** [cruizperez/MicrobeAnnotator#15]
I have tried to create the MicrobeAnnotator with and without Aspera, using the conda installation (v2.0.5) as well as pip installation (v2.0.4) and I keep getting the following errors on step 9 (steps 1-8 worked returned no errors):

With Aspera:
```
2021-05-03 11:59:58,370 [INFO]: This is MicrobeAnnotator v2.0.5
2021-05-03 11:59:58,371 [INFO]: I will download and format the databases I use.
2021-05-03 11:59:58,371 [INFO]: Creating database folders
2021-05-03 11:59:58,371 [INFO]: Step 9
2021-05-03 11:59:58,371 [INFO]: Downloading protein fasta files using Aspera Connect.
Traceback (most recent call last):
  File "/gpfs1/scratch/ryan/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/gpfs1/scratch/ryan/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/gpfs1/scratch/ryan/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 175, in database_duilder
    refseq_prot = refseq.refseq_fasta_downloader(database_directory)
  File "/gpfs1/scratch/ryan/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/refseq_data_downloader.py", line 61, in refseq_fasta_downloader
    ascp_key = get_aspera_key()
  File "/gpfs1/scratch/ryan/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/refseq_data_downloader.py", line 277, in get_aspera_key
    install_folder = Path(path_to_ascp).parents[1]
  File "/gpfs1/scratch/ryan/miniconda3/envs/microbeannotator/lib/python3.7/pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "/gpfs1/scratch/ryan/miniconda3/envs/microbeannotator/lib/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/gpfs1/scratch/ryan/miniconda3/envs/microbeannotator/lib/python3.7/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Without Aspera (`--no_aspera` flag):
```
2021-04-30 16:48:40,896 [INFO]: This is MicrobeAnnotator v2.0.4
2021-04-30 16:48:40,896 [INFO]: I will download and format the databases I use.
2021-04-30 16:48:40,896 [INFO]: Creating database folders
2021-04-30 16:48:40,897 [INFO]: Step 9
2021-04-30 16:48:40,897 [INFO]: Downloading protein fasta files using wget.
2021-04-30 19:36:28,292 [INFO]: Merging protein files
Traceback (most recent call last):
  File "/gpfs1/apps/anaconda/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/gpfs1/apps/anaconda/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/gpfs1/apps/anaconda/envs/microbeannotator/bin/microbeannotator_db_builder", line 178, in database_duilder
    database_directory, threads)
  File "/gpfs1/apps/anaconda/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/refseq_data_downloader.py", line 162, in refseq_fasta_downloader_wget
    copyfileobj(temp_file,merged_db)
  File "/gpfs1/apps/anaconda/envs/microbeannotator/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/gpfs1/apps/anaconda/envs/microbeannotator/lib/python3.7/gzip.py", line 300, in read1
    return self._buffer.read1(size)
  File "/gpfs1/apps/anaconda/envs/microbeannotator/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/gpfs1/apps/anaconda/envs/microbeannotator/lib/python3.7/gzip.py", line 482, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid code lengths set
```

**Comment by cruizperez** [comment]
Hi @ryanjameskennedy
Is this building with the --light flag, or building the entire database?

**Comment by ryanjameskennedy** [comment]
The entire database. Which I am aware is ~237Gb and have made sure I have enough space.

**Comment by sipesk** [comment]
I also had this error, I am wondering if you solved it somehow, ryanjameskennedy ?

> The entire database. Which I am aware is ~237Gb and have made sure I have enough space.

**Comment by cruizperez** [comment]
This is very weird. I am trying to replicate the issue but it runs ok for me. I contacted uniprot support to see if this is something on their side and I will get back to you asap.

**Comment by dschnei1** [comment]
Dear cruizperez,
I get the same error message as ryanjameskennedy (also trying to setup the entire db) - do you have any idea how to solve this?

**Comment by B47895** [comment]
Hello there
I am getting the same error messages downloading the full database. Hoping we'll have a solution :)

**Comment by hlykkk** [comment]
Dear cruizperez,
I want to setup the entire db, but I get the same error at step 9, any solution ?

**Comment by scrosson73** [comment]
I'm also getting the same error message with Aspera at step 9, and a similar message (below) without Aspera at Step 9:

uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: too many length or distance symbols

**Comment by IWasBorg** [comment]
Same error message too with Aspera at Step 9. What did the developers do to avoid that problem? Since they had a smooth sailing building the DB unlike we do

**Comment by cruizperez** [comment]
Hi everyone. For some reason I was not getting emails about this and I just checked the repo. Let me look more into this and get back to all of you.

**Comment by angeliqueray** [comment]
Hi everyone, I've been having the same issue. I'm looking forward to seeing how this problem can be solved.

**Comment by angeliqueray** [comment]
Is there any news regarding this issue?

**Comment by nihesh7391** [comment]
@angeliqueray 

I also faced the same issue!
While going trough the code/error message, I figured out that the problem was caused by the line number 61 in microbeannotator/database/refseq_data_downloader.py file. 
"ascp_key = get_aspera_key()"

So, I changed it to: 
ascp_key = "/home/[username]/.aspera/connect/etc/asperaweb_id_dsa.openssh"

Did the same thing for line number 186.
For some weird reason, this solved the problem.

Hopefully, this helps!

**Comment by silvtal** [comment]
> I had the same issue and solved it by adding aspera to path.
> 
> Make sure that Aspera added to your path.
> 
> ```
> (Usually it will be installed in your home under your user in "/home/[user]/.aspera/connect/bin", it will show you where)
> 
> Take note of this installation folder and, for your peace of mind lets add this folder to your PATH:
> 
> Add the following line to your ~/.bashrc file: export PATH="$PATH:/home/[user]/.aspera/connect/bin"
> Note: Replace [user] by your username
> 
> Now reload the ~/.bashrc file with: source ~/.bashrc
> 
> Now you have installed Aspera Connect!
> ```

This helped, thank you !
