### ISSUE TITLE
Kofam database source not found during building

### ISSUE THREAD

**Issue by Robaina** [cruizperez/MicrobeAnnotator#18]
Hi!

MicrobeAnnotator looks very cool! However, I haven't been able to build the database. I installed MicrobeAnnotator via conda, then attempted to build database (the light version) with: 

microbeannotator_db_builder -d MicrobeAnnotator_DB -m sword -t 14 --light

Apparently, there is some error trying to download the KOfam data. Any ideas? Thanks!

---
2021-05-11 16:52:47,727 [INFO]: This is MicrobeAnnotator v2.0.5
2021-05-11 16:52:47,727 [INFO]: I will download and format the databases I use.
2021-05-11 16:52:47,727 [INFO]: Creating database folders
2021-05-11 16:52:47,727 [INFO]: Step 1
2021-05-11 16:52:47,727 [INFO]: Downloading KOfam data
2021-05-11 16:52:48,393 Aquifex microbeannotator.database.kofam_profile_parser: Function: kofam_downloader - Line: 76 [WARNING]: Data not available from kofam source. Using backup data from XXX
2021-05-11 16:52:49,058 Aquifex microbeannotator.database.kofam_profile_parser: Function: kofam_downloader - Line: 88 [WARNING]: Data not available from kofam source. Using backup data from XXX
2021-05-11 16:52:49,059 [INFO]: Finished
2021-05-11 16:52:49,059 [INFO]: Step 2
2021-05-11 16:52:49,059 [INFO]: Formatting KOfam profiles
Traceback (most recent call last):
  File "/home/robaina/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/home/robaina/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/home/robaina/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 97, in database_duilder
    kofam.kofam_formatter(ko_profiles_path)
  File "/home/robaina/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/kofam_profile_parser.py", line 112, in kofam_formatter
    with open(ko_profiles_path_extr / 'prokaryote.hal', 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'MicrobeAnnotator_DB/kofam_data/profiles/prokaryote.hal'

**Comment by eddykay310** [comment]
Try to specify the full path length to the MicrobeAnnotator_DB directory

eg: microbeannotator_db_builder -d /home/user/microbeannotator/MicrobeAnnotator_DB -m sword -t 14 --light

**Comment by Robaina** [comment]
Thanks, already tried that... seems like there is some issue with the KOfam database perhaps... having trouble downloading it manually from their server too (ftp://ftp.genome.jp/pub/tools/kofam_scan)

Anyone getting similar results?

**Comment by cruizperez** [comment]
Hi @Robaina 
Sorry for the late response. I have seen this happen when the server where Kofam data is located is down. I suspect this is the case as you are also unable to download the data manually. I am working on uploading a backup on our site, but I first need to check if this is allowed. I would recommend you try again and I will give you an update on this issue soon.

**Comment by Robaina** [comment]
Hey, ok, yeah seems like an issue with Kofam... if allowed would be helpful to include Kofam data in MicrobeAnnotator, I know it's not always possible though.

Thanks,
Semidán

**Comment by DalimilBujdos** [comment]
Hello @cruizperez excellent tool,

I am running into the same problem (1st October 2021). Were you able to resolve the it @Robaina?

Thanks

**Comment by khirai** [comment]
our institution instituted a firewall policy that doesn't allow outgoing ftp connections without asking for an exception. is there a static list of ftp sources i can hand them? i was able to grep these out of 
lib/python3.7/site-packages/microbeannotator/database
ftp.genome.jp
ftp.ebi.ac.uk
ftp.ncbi.nlm.nih
ftp.uniprot.org
still waiting for my ticket to be processed so i don't know for sure if this is broad enough. but is it too broad?
