### ISSUE TITLE
Db builder error

### ISSUE THREAD

**Issue by fetyj** [cruizperez/MicrobeAnnotator#2]
Hi,
I want to annotate some bacteria genomes and your great tool seems the right one. I'm trying to build the light database but I encounter this error, could you help me? Thanks for your help
Regards,
Fety
```
./MicrobeAnnotator_DB_Builder -d MicrobeAnnotator_DB -m sword --light -t 16
Downloading UniProt information...
Downloading fasta files...
100% [....................................................] 89237849 / 89237849
Done
Downloading .dat files...
100% [..................................................] 589192693 / 589192693
Done
Finished downloading UniProt data!
Traceback (most recent call last):
  File "./MicrobeAnnotator_DB_Builder", line 177, in <module>
    main()
  File "./MicrobeAnnotator_DB_Builder", line 173, in main
    db_duilder(directory, method, light, threads, step, bin_path)
  File "./MicrobeAnnotator_DB_Builder", line 58, in db_duilder
    viral_list = refseq_data_downloader.search_all_files(temp_gb_files / "viral")
  File "/home/fiestaj/MicrobeAnnotator/independent_scripts/refseq_data_downloader.py", line 107, in search_all_files
    assert(dirpath.is_dir())
AssertionError```

**Comment by fetyj** [comment]
I got pass the error by deleting line 55 to line 61 in the ``` MicrobeAnnotator_DB_Builder```
Now running my annotation, I got this error message: 
```---- This is MicrobeAnnotator ----
I will process a total of 1 files. Of these, I will run 1 in parallel with 1 threads per file.
For this run I will use KOFamscan and the Swissprot database to annotate your proteins.
When I'm done I will plot the metabolism summaries using metabolic_summary_ as file name prefix using no clustering.
---------

Searching proteins using KOFamscan...
Error: KO list not given
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/fiestaj/anaconda3/envs/microbeannotator/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fiestaj/anaconda3/envs/microbeannotator/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/fiestaj/MicrobeAnnotator/independent_scripts/protein_search.py", line 52, in kofamscan_annotation
    kofamscan_filter(kofam_output_file, filtered_output_file)
  File "/home/fiestaj/MicrobeAnnotator/independent_scripts/protein_search.py", line 80, in kofamscan_filter
    with open(kofamscan_input, 'r') as input:
FileNotFoundError: [Errno 2] No such file or directory: '/choppy/Bacteria_assembly/Lb_rhamnosus/5326_micann/kofamscan_results/5326_hyb.faa.kofam'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./MicrobeAnnotator", line 409, in <module>
    main()
  File "./MicrobeAnnotator", line 140, in main
    kofam_results = pool.map(partial(protein_search.kofamscan_annotation, 
  File "/home/fiestaj/anaconda3/envs/microbeannotator/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/fiestaj/anaconda3/envs/microbeannotator/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/choppy/Bacteria_assembly/Lb_rhamnosus/5326_micann/kofamscan_results/5326_hyb.faa.kofam '
```
Here is my command : 
```./MicrobeAnnotator -i /choppy/Bacteria_assembly/Lb_rhamnosus/5326_hyb.faa -d /home/fiestaj/MicrobeAnnotator/MicrobeAnnotator_DB -o /choppy/Bacteria_assembly/Lb_rhamnosus/5326_micann -m sword --light```

Thanks,
Fety

**Comment by cruizperez** [comment]
Hi Fety!
Thanks for testing MicrobeAnnotator! I am currently finishing the program so I'm sure some bugs will arise (as you found already). The first error you encountered has been corrected, it was just the order of the command that checked the existence of a group of files. You can update your repo and see if it works. The second I think is related to kofamscan. I added a check at the beginning to see if the paths are correct, but I suspect this has to do with hmmer. I've had cases in which hmmsearch is not found and kofamscan will apparently run fine but no output will be created. Can you check if hmmsearch is in your path and is accessed by kofamscan in the config file? Let me know what you get. 
Thanks!

**Comment by fetyj** [comment]
Hi,
Thanks for the reply and the fix! I'm actually on holidays so no access to my computer but I'll let you know how it's work as soon as I can.
Fety

**Comment by fetyj** [comment]
Hi,
After updating my repo, everything works just fine for Db builder. I've change also the hmmsearch path in the config file from ```/usr/local/bin/hmmsearch``` to ```/home/fiestaj/anaconda3/envs/microbeannotator/bin/hmmsearch``` and so for ```parallel```
After re-running the same command I got new error message, hope you can help with that one:
```---- This is MicrobeAnnotator ----
I will process a total of 1 files. Of these, I will run 1 in parallel with 1 threads per file.
For this run I will use KOFamscan and the Swissprot database to annotate your proteins.
When I'm done I will plot the metabolism summaries using metabolic_summary_ as file name prefix using no clustering.
---------

Searching proteins using KOFamscan...
Error: KO list not given
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/fiestaj/anaconda3/envs/microbeannotator/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fiestaj/anaconda3/envs/microbeannotator/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/fiestaj/MicrobeAnnotator/independent_scripts/protein_search.py", line 52, in kofamscan_annotation
    kofamscan_filter(kofam_output_file, filtered_output_file)
  File "/home/fiestaj/MicrobeAnnotator/independent_scripts/protein_search.py", line 81, in kofamscan_filter
    with open(kofamscan_input, 'r') as input:
FileNotFoundError: [Errno 2] No such file or directory: '/choppy/Bacteria_assembly/Lb_rhamnosus/5326_micann/kofamscan_results/5326_hyb.faa.kofam'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./MicrobeAnnotator", line 439, in <module>
    main()
  File "./MicrobeAnnotator", line 170, in main
    kofam_results = pool.map(partial(protein_search.kofamscan_annotation, 
  File "/home/fiestaj/anaconda3/envs/microbeannotator/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/fiestaj/anaconda3/envs/microbeannotator/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/choppy/Bacteria_assembly/Lb_rhamnosus/5326_micann/kofamscan_results/5326_hyb.faa.kofam'
```
Thanks
Fety

**Comment by cruizperez** [comment]
Hi Fety!

Could you share the contents of the config file from KOfamscan?

Carlos

**Comment by fetyj** [comment]
Hi Carlos,
Here is the contents: 
```
# Path to your KO-HMM database
# A database can be a .hmm file, a .hal file or a directory in which
# .hmm files are. Omit the extension if it is .hal or .hmm file
# profile: /home/fiestaj/kofamscan/profiles/prokaryote

# Path to the KO list file
# ko_list: /home/fiestaj/kofamscan/ko_list

# Path to an executable file of hmmsearch
# You do not have to set this if it is in your $PATH
# hmmsearch: /home/fiestaj/anaconda3/envs/microbeannotator/bin/hmmsearch

# Path to an executable file of GNU parallel
# You do not have to set this if it is in your $PATH
# /home/fiestaj/anaconda3/envs/microbeannotator/bin/parallel

# Number of hmmsearch processes to be run parallelly
cpu: 8
```

Fety

**Comment by cruizperez** [comment]
Hi Fety!
Just remove the # from all the lines where you have modified the paths. In this file the # is treated as comments as the program ignores those lines. Let me know if it works! 😁

Carlos

**Comment by fetyj** [comment]
It works like a charm :-), I did not pay attention to the file format. 
Thanks for your help and the tools. 

Fety
