### ISSUE TITLE
Creating output_file matrix and heatmap

### ISSUE THREAD

**Issue by eddykay310** [cruizperez/MicrobeAnnotator#20]
Hi, can you kindly help me with this error. Seems seaborn has issues with making the plots.

Thank you

#####################

Creating output_file matrix and heatmap...
There are no modules above 50% completeness. Plotting all modules regardless of completeness.
Traceback (most recent call last):
  File "/root/miniconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/root/miniconda3/envs/microbeannotator/bin/microbeannotator", line 971, in main
    metabolism_matrix_dropped_relabel, module_colors = ko_mapper.create_output_files(metabolic_annotation, metabolism_matrix, module_information, cluster, prefix)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/ko_mapper.py", line 568, in create_output_files     
    cbar_kws= {'orientation': 'horizontal', 'label': 'Module Completeness (%)'}, dendrogram_ratio=0.1)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/seaborn/matrix.py", line 1412, in clustermap
    tree_kws=tree_kws, **kwargs)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/seaborn/matrix.py", line 1234, in plot
    self.plot_matrix(colorbar_kws, xind, yind, **kws)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/seaborn/matrix.py", line 1187, in plot_matrix
    xticklabels=xtl, yticklabels=ytl, annot=annot, **kws)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/seaborn/matrix.py", line 537, in heatmap
    yticklabels, mask)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/seaborn/matrix.py", line 156, in __init__
    cmap, center, robust)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/seaborn/matrix.py", line 194, in _determine_cmap_params
    vmin = np.nanmin(calc_data)
  File "<__array_function__ internals>", line 6, in nanmin
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 319, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, **kwargs)
ValueError: zero-size array to reduction operation fmin which has no identity

**Comment by cruizperez** [comment]
Hi @eddykay310!
Would it be possible for you to share the results of the annotation? Mostly the KO identifiers so I can debug it? Thanks!

**Comment by eddykay310** [comment]
Any mail I can send the files to?

Thanks

**Comment by eddykay310** [comment]
Also I would like to ask what could be the reason for getting the same set of genes in the metabolic_summary__module_completeness tab file after running the analysis. I used two different fasta files but got the same output

**Comment by EricDeveaud** [comment]
same problem here.

@cruizperez can you provide a small data set for testin purpose ? 

regards
Eric
