### ISSUE TITLE
Issues with searching Swissprot

### ISSUE THREAD

**Issue by eddykay310** [cruizperez/MicrobeAnnotator#25]
Hi @cruizperez 

Please help me understand the problem here and how I can fix it. I have successfully generated my DBs but I get this error during analysis. The .dmnd files do not exist in the folders as the error says but I don't know how I can generate them and if it was a problem with the DB creation

#######################################################################
2021-07-05 22:32:51,947 [INFO]: Step 2
2021-07-05 22:32:51,947 [INFO]: Searching proteins against Swissprot
No such file or directory
No such file or directory
Error: Error: Error calling stat on file /mnt/e/MicrobeAnnotator_DB/protein_db/uniprot_sprot.dmndError calling stat on file /mnt/e/MicrobeAnnotator_DB/protein_db/uniprot_sprot.dmnd

No such file or directory
No such file or directory
Error: Error calling stat on file /mnt/e/MicrobeAnnotator_DB/protein_db/uniprot_sprot.dmndError:
Error calling stat on file /mnt/e/MicrobeAnnotator_DB/protein_db/uniprot_sprot.dmnd
No such file or directory
No such file or directory
Error: Error: Error calling stat on file /mnt/e/MicrobeAnnotator_DB/protein_db/uniprot_sprot.dmndError calling stat on file /mnt/e/MicrobeAnnotator_DB/protein_db/uniprot_sprot.dmnd

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 232, in similarity_search
    blast_filter_slow(method_output_file, filtered_file, id_perc, bitscore, evalue, aln_percent)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 138, in blast_filter_slow
    with open(input_tab) as blast_input:
FileNotFoundError: [Errno 2] No such file or directory: 'MA_output/swissprot_results/cdsAA.fasta.step_2.diamond'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/root/miniconda3/envs/microbeannotator/bin/microbeannotator", line 429, in main
    multiple_arguments=arguments_to_pass), input_proteins)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'MA_output/swissprot_results/dsAA.fasta.step_2.diamond'
###########################################################

Thank you

**Comment by silvtal** [comment]
I see you closed the issue. Do you remember what the problem was?

**Comment by eddykay310** [comment]
I can't remember how I fixed this issue. I probably didn't get help in time and after getting it to work I forgot to put the solution here. But thanks @silvtal, it would help someone down the line who encounters a similar problem.
