### ISSUE TITLE
No such table: refseq

### ISSUE THREAD

**Issue by eddykay310** [cruizperez/MicrobeAnnotator#26]
Hi @cruizperez 

Please what could the problem be? 

#############################
2021-07-06 09:32:02,389 [INFO]: Searching proteins against RefSeq
2021-07-07 08:15:51,490 [INFO]: Extracting RefSeq annotation data
Traceback (most recent call last):
  File "/root/miniconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/root/miniconda3/envs/microbeannotator/bin/microbeannotator", line 666, in main
    refdata.microbeannotator_db, "refseq", significant_hits)
  File "/root/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/sqlite3_search.py", line 135, in search_ids_imported
    cur.execute("SELECT * FROM " + database_table + " WHERE gene_id=?", (gene_id,))
sqlite3.OperationalError: no such table: refseq
###############################

Thank you

**Comment by cruizperez** [comment]
It seems a table is missing from the sqlite db, are you certain the db building step finished successfully?

**Comment by eddykay310** [comment]
Can this be the cause?

2021-07-05 15:03:10,177 [INFO]: Parsing RefSeq KO numbers
100% [......................................................................] 954001401 / 954001401Segmentation fault (core dumped)

**Comment by eddykay310** [comment]
The db making process stops after the above line in the terminal. I don't know why but I continued with the rest of the steps after and they seem to work fine but when I started the analysis I got the error in the first first comment.

**Comment by eddykay310** [comment]
@cruizperez any help

**Comment by cruizperez** [comment]
Sorry for the delay in my responses! I am moving so its a bit crazy right now. You could try re doing that particular step in the db building command.

**Comment by eddykay310** [comment]
Oh ok. My bad. No problem 

I have tried a number of times but the db building just quits at this step, which is step 12. I don't know what the issue could be.
