### ISSUE TITLE
search_results referenced before assignment

### ISSUE THREAD

**Issue by ctxchris** [cruizperez/MicrobeAnnotator#29]
Hi,

I'm running microbeannotator v2.0.5 installed via conda:

`microbeannotator -i prot.fasta -o results -d /software/microbeannotator/database -m sword -t 50 --refine --full `

and get the following error message:

>  ---- This is MicrobeAnnotator v2.0.5 ---- 
> Validating user inputs
> Passed
> Processing 1 files. I will run 1 files in parallel with 50 threads per file.
> Searching proteins against KOfam profiles
> Parsing HMM profile metadata
> Filtering and saving results...
> Search against KOfam done!
> Searching proteins against Swissprot
> Extracting Swissprot annotation data
> Searching proteins against RefSeq
> 
> Traceback (most recent call last):
>   File "anaconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
>     main()
>   File "/anaconda3/envs/microbeannotator/bin/microbeannotator", line 635, in main
>     for result in search_results:
> UnboundLocalError: local variable 'search_results' referenced before assignment

Thanks,
Chris

**Comment by mike-bioinfo** [comment]
I'm having the same issue... Anyone can help us?

**Comment by asbhattacharjee** [comment]
**I'm also having the same issue.**

Log
2022-04-29 21:52:10,985 [INFO]:  ---- This is MicrobeAnnotator v2.0.5 ----                                                                                                     2022-04-29 21:52:10,985 [INFO]: Validating user inputs                                                                                                                         2022-04-29 21:52:10,985 [INFO]: Passed                                                                                                                                         2022-04-29 21:52:10,986 [INFO]: Processing 9 files. I will run 3 files in parallel with 10 threads per file.                                                                   2022-04-29 21:52:11,470 [INFO]: Searching proteins against KOfam profiles                                                                                                      2022-04-29 21:52:11,470 [INFO]: Parsing HMM profile metadata                                                                                                                   2022-04-29 21:53:15,519 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 21:53:15,646 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 21:53:54,891 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 21:53:54,968 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 21:54:52,914 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 21:54:53,023 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 21:55:40,313 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 21:55:40,429 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 21:56:15,548 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 21:56:15,603 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 21:57:57,050 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 21:57:57,148 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 21:58:03,669 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 21:58:03,675 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 21:58:15,086 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 21:58:15,098 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 22:00:31,180 [INFO]: Filtering and saving results...                                                                                                                2022-04-29 22:00:31,240 [INFO]: Search against KOfam done!                                                                                                                     2022-04-29 22:00:31,257 [INFO]: Searching proteins against Swissprot                                                                                                           2022-04-29 22:00:31,257 [INFO]: Extracting Swissprot annotation data                                                                                                           2022-04-29 22:00:31,257 [INFO]: Searching proteins against RefSeq                                                                                                              Traceback (most recent call last):                                                                                                                                               
File "/rhome/anandab/.conda/envs/microbeannotatorV2/bin/microbeannotator", line 981, in <module>                                                                                 main()                                                                                                                                                                       
File "/rhome/anandab/.conda/envs/microbeannotatorV2/bin/microbeannotator", line 635, in main                                                                                     for result in search_results:                                                                                                                                              UnboundLocalError: local variable 'search_results' referenced before assignment

I can provide the log files if that would help. 
Thanks in advance!

**Comment by bdaisley** [comment]
I recently ran into this issue when running the `--full` version of the pipeline and tracked it down to a python indentation error. Sharing the solution here in case it can help anyone else @davidecarlson @asbhattacharjee @mike-bioinfo @ctxchris @lmrodriguezr @cruizperez

The error originates in the [MicrobeAnnotator/bin/microbeannotator](https://github.com/cruizperez/MicrobeAnnotator/tree/master/bin/microbeannotator) script. Specifically, everything between lines 629-639 needs to be indented so that `search_results` on line 623 is recognized as being assigned before then referencing `search_results` on line 635. The default in python is four spaces for indentation.
 
### So, simply add 4 spaces at the start of lines 629-639 to fix the issue. 

E.g., Original code snippet from [MicrobeAnnotator/bin/microbeannotator](https://github.com/cruizperez/MicrobeAnnotator/tree/master/bin/microbeannotator) script (accessed on 08-Aug-2023):
```
617             if len(input_proteins) > 0:
618                 try:
619                     pool = multiprocessing.Pool(processes)
620                     arguments_to_pass = (
621                         outdir, 'refseq', refdata.refseq_db, method, threads,
622                         id_perc, bitscore, evalue, aln_percent, method_bin)
623                     search_results = pool.map(partial(search.similarity_search,
624                     multiple_arguments=arguments_to_pass), input_proteins)
625                     # Results as (protein_file, filtered_search_file)
626                 finally:
627                     pool.close()
628                     pool.join()
629             # Add name of filtered_search_results to protein_file_info
630             # New structure:
631             # protein_file : [protein_file_name, final_annotation_file,
632             # kofam_results, fasta_step_2, Swissprot_Search_File,
633             # fasta_step_3, RefSeq_Search_File]
634             temp_dir = protein_file_info.copy()
635             for result in search_results:
636                 for filename, info in temp_dir.items():
637                     if len(info) == 6 and result[0] == info[5]:
638                         protein_file_info[filename].append(result[1])
639             del temp_dir
640             # Search annotations in SQLite DB and
641             # append to the final annotation file
642             logger.info("Extracting RefSeq annotation data")
```

Corrected with proper indentation between lines 629-639.
```
617             if len(input_proteins) > 0:
618                 try:
619                     pool = multiprocessing.Pool(processes)
620                     arguments_to_pass = (
621                         outdir, 'refseq', refdata.refseq_db, method, threads,
622                         id_perc, bitscore, evalue, aln_percent, method_bin)
623                     search_results = pool.map(partial(search.similarity_search,
624                     multiple_arguments=arguments_to_pass), input_proteins)
625                     # Results as (protein_file, filtered_search_file)
626                 finally:
627                     pool.close()
628                     pool.join()
629                 # Add name of filtered_search_results to protein_file_info
630                 # New structure:
631                 # protein_file : [protein_file_name, final_annotation_file,
632                 # kofam_results, fasta_step_2, Swissprot_Search_File,
633                 # fasta_step_3, RefSeq_Search_File]
634                 temp_dir = protein_file_info.copy()
635                 for result in search_results:
636                     for filename, info in temp_dir.items():
637                         if len(info) == 6 and result[0] == info[5]:
638                             protein_file_info[filename].append(result[1])
639                 del temp_dir
640             # Search annotations in SQLite DB and
641             # append to the final annotation file
642             logger.info("Extracting RefSeq annotation data")
```

You will have to make these adjustments locally to your microbeannotator script. If you installed via conda environment, the script can be found in the 'envs' directory. On my linux system the file of interest was located at "/home/bdaisley/miniconda/envs/microbeannotator/bin/microbeannotator". Navigate to the appropriate directory on your own system, edit the lines as above, and save the file. 

### Note: You will notice after fixing this issue that another (identical) error, i.e., `UnboundLocalError: local variable 'search_results' referenced before assignment`, occurs during the next TrEMBL searching step that follows. 

This time, the identation error stems from lines 760-770. Add 4 spaces at the start of each of these lines to resolve the issue.

E.g., Original code snippet from [MicrobeAnnotator/bin/microbeannotator](https://github.com/cruizperez/MicrobeAnnotator/tree/master/bin/microbeannotator) script (accessed on 08-Aug-2023):
```
748        if len(input_proteins) > 0:
749            try:
750                pool = multiprocessing.Pool(processes)
751                arguments_to_pass = (
752                    outdir, 'trembl', refdata.trembl_db, method, threads,\
753                    id_perc, bitscore, evalue, aln_percent, method_bin)
754                search_results = pool.map(partial(search.similarity_search,
755                multiple_arguments=arguments_to_pass), input_proteins)
756                # Results as (protein_file, filtered_search_file)
757            finally:
758                pool.close()
759                pool.join()
760        # Add name of filtered_search_results to protein_file_info
761        # New structure:
762        # protein_file : [protein_file_name, final_annotation_file,
763        # kofam_results, fasta_step_2, Swissprot_Search_File,
764        # fasta_step_3, RefSeq_Search_File, fasta_step_4, Trembl_Search_File]
765        temp_dir = protein_file_info.copy()
766        for result in search_results:
767            for filename, info in temp_dir.items():
768                if len(info) == 8 and result[0] == info[6]:
769                    protein_file_info[filename].append(result[1])
770        del temp_dir
771        # Search annotations in SQLite DB and
772        # append to the final annotation file
773        logger.info("Extracting Trembl annotation data")
```

Corrected with proper indentation between lines 760-770.
```
748        if len(input_proteins) > 0:
749            try:
750                pool = multiprocessing.Pool(processes)
751                arguments_to_pass = (
752                    outdir, 'trembl', refdata.trembl_db, method, threads,\
753                    id_perc, bitscore, evalue, aln_percent, method_bin)
754                search_results = pool.map(partial(search.similarity_search,
755                multiple_arguments=arguments_to_pass), input_proteins)
756                # Results as (protein_file, filtered_search_file)
757            finally:
758                pool.close()
759                pool.join()
760            # Add name of filtered_search_results to protein_file_info
761            # New structure:
762            # protein_file : [protein_file_name, final_annotation_file,
763            # kofam_results, fasta_step_2, Swissprot_Search_File,
764            # fasta_step_3, RefSeq_Search_File, fasta_step_4, Trembl_Search_File]
765            temp_dir = protein_file_info.copy()
766            for result in search_results:
767                for filename, info in temp_dir.items():
768                    if len(info) == 8 and result[0] == info[6]:
769                        protein_file_info[filename].append(result[1])
770            del temp_dir
771        # Search annotations in SQLite DB and
772        # append to the final annotation file
773        logger.info("Extracting Trembl annotation data")
```

Hopefully this can help others, let me know if any questions.
