### ISSUE TITLE
Receiving a error Signals.SIGABRT: 6

### ISSUE THREAD

**Issue by passimtushar10** [cruizperez/MicrobeAnnotator#30]
Hello,

I am running MicrobeAnnotator v2.0.5 installed using conda.

microbeannotator -i $(ls *.fasta) -d removableDisk2/MicrobeAnnotator_DB -o MicrobeAnno -m sword -p 2 -t 5

and get the following error message:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dnd/miniconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/home/dnd/miniconda3/envs/microbeannotator/bin/microbeannotator", line 367, in main
    processes=processes, threads=threads)
  File "/home/dnd/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/hmmsearch.py", line 192, in hmmsearch_launcher
    hmmer_search, protein_model_list)
  File "/home/dnd/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/dnd/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '['/home/dnd/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/bin/v3.3.2/hmmsearch_manylinux2010_x86_64', '-o', '/tmp/tmp2yf_l08yKUX3GWH3JNPYDEOMC34D', '--tblout', '/tmp/tmph1yqkwpa/tbl.txt', '--domtblout', '/tmp/tmph1yqkwpa/domtbl.txt', '/media/dnd/removableDisk2/MicrobeAnnotator_DB/kofam_data/profiles/common_1.model', '/home/group1/tushar/Genomes_nt_Alka/1.fasta']' died with <Signals.SIGABRT: 6>.

Please help me out.

**Comment by devarajarun** [comment]
I'm having the same issue. Developer, please assist us if you know anything about the issue. Thanks.

**Comment by tbazilegith** [comment]
Hello Rotheconrad,
Any update ragarding the above issue?
Thanks, 
TJ
