### ISSUE TITLE
missing file for restart and out of memory

### ISSUE THREAD

**Issue by soilmicrobiome** [cruizperez/MicrobeAnnotator#42]
Hi there,

I have two issues trying to get my data to run.  I am running version 2.0.4 on an HPC:

Issue 1: I gave my job 71 hours but it did not get past the Kofam stage (see below).  

```
2022-01-08 07:13:01,253 [INFO]:  ---- This is MicrobeAnnotator v2.0.4 ---- 
2022-01-08 07:13:01,254 [INFO]: Validating user inputs
2022-01-08 07:13:01,293 [INFO]: Passed
2022-01-08 07:13:01,294 [INFO]: Processing 1 files. I will run 1 files in parallel with 32 threads per file.
2022-01-08 07:13:09,946 [INFO]: Searching proteins against KOfam profiles
2022-01-08 07:13:09,946 [INFO]: Parsing HMM profile metadata
2022-01-08 10:30:21,945 [INFO]: Filtering and saving results...
2022-01-08 10:30:46,116 [INFO]: Search against KOfam done!
slurmstepd: error: *** JOB 56466780 ON gra996 CANCELLED AT 2022-01-11T07:11:46 DUE TO TIME LIMIT ***
```

Then i use the restart option i get a "missing files"  error.  

```
2022-01-12 12:52:10,902 [INFO]:  ---- This is MicrobeAnnotator v2.0.4 ---- 
2022-01-12 12:52:10,903 [INFO]: Validating user inputs
2022-01-12 12:52:10,940 [INFO]: Passed
2022-01-12 12:52:10,940 [INFO]: Processing 1 files. I will run 1 files in parallel with 32 threads per file.
2022-01-12 12:52:11,110 [INFO]: Restarting from last checkpoint
Traceback (most recent call last):
  File "/home/user/microbannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/home/user/microbannotator/bin/microbeannotator", line 299, in main
    with open(process_log_folder / "log.txt", 'r') as logfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/projects/def-user/user/lakes/short_cores/annotation/microbeannotator_sample1/process_log/log.txt'
```

I next decided to try the whole process from the start but give the job more time, and split the number of files with the -p option:
```
```
#!/bin/bash
#SBATCH --mem=256500M
#SBATCH --nodes=1
#SBATCH --account=def-user
#SBATCH --cpus-per-task=24
#SBATCH --time=0-71:59
```
module load python/3.7 StdEnv/2020 scipy-stack/2021a gcc/9.3.0 blast+/2.12.0 diamond/2.0.9
source /home/user/microbannotator/bin/activate
export PATH="$PATH":/home/user/microbannotator/sword/build/bin/
microbeannotator -i /home/user/projects/def-user/user/lakes/short_cores/annotation/orfs.faa -o /home/user/projects/def-user/user/lakes/short_cores/annotation/microbeannotator_sample1/ -d /home/user/projects/def-user/databases_software/microbeannotator/12_06_m_a_sword/ -m sword -p 2 -t 12 --continue_run
```

But now i am facing a missing file/memory issue:

```
2022-01-12 08:29:06,135 [INFO]:  ---- This is MicrobeAnnotator v2.0.4 ---- 
2022-01-12 08:29:06,135 [INFO]: Validating user inputs
2022-01-12 08:29:06,164 [INFO]: Passed
2022-01-12 08:29:06,164 [INFO]: Processing 1 files. I will run 2 files in parallel with 12 threads per file.
2022-01-12 08:29:06,315 [INFO]: Restarting from last checkpoint
2022-01-12 08:29:06,359 [INFO]: Step 2
2022-01-12 08:29:06,368 [INFO]: Searching proteins against Swissprot
[381640]-[420597]: max = 444, groups = 1631, time = 20907.83190 s
[420597]-[455288]: max = 499, groups = 1792, time = 20920.99731 s
[512245]-[534054]: max = 840, groups = 2788, time = 20952.81049 s
[337389]-[381640]: max = 394, groups = 1485, time = 20989.27547 s
[455288]-[485953]: max = 572, groups = 2005, time = 21015.30722 s
[534054]-[551365]: max = 1099, groups = 3545, time = 21038.17926 s
[485953]-[512245]: max = 677, groups = 2312, time = 21102.46282 s
[286739]-[337389]: max = 346, groups = 1345, time = 21579.63581 s
[226092]-[286739]: max = 298, groups = 1205, time = 22618.61195 s
[551365]-[563131]: max = 2000, groups = 6182, time = 22642.74551 s
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.9/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.9/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/user/microbannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 250, in similarity_search
    add_query_len(method_output_file, protein_file, temporal_file)
  File "/home/user/microbannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 169, in add_query_len
    with open(input_tab, 'r') as blast_like, open(outfile, 'w') as output:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/projects/def-user/user/lakes/short_cores/annotation/microbeannotator_sample1/swissprot_results/orfs.faa.step_2.sword'
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/microbannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/home/user/microbannotator/bin/microbeannotator", line 429, in main
    multiple_arguments=arguments_to_pass), input_proteins)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.9/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.7.9/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/projects/def-user/user/lakes/short_cores/annotation/microbeannotator_sample1/swissprot_results/orfs.faa.step_2.sword'
slurmstepd: error: Detected 2 oom-kill event(s) in StepId=56537688.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

Any thoughts what these issues are?  or how to fix?

**Comment by rotheconrad** [comment]
Have you retried running the 1st way? delete the 1st attempt and then try it again?

I have had MicrobeAnnotator get hung up at the Kofam step twice (out of many different runs) on our HPC. Instead of trying the restart option I just deleted the files and tried again and it worked.

I would like to rule that out before speculating further.

The -p options does not split the input file for you. That option is if you give it multiple input fasta you can process multiple genomes (protein fastas) simultaneously. So the error there is likely because you provide one input file put specify -p 2.

**Comment by soilmicrobiome** [comment]
I ended up using diamond and not sword.  My job worked that way.

Thanks for the info!
