### ISSUE TITLE
Step 9 - Merging proteins files

### ISSUE THREAD

**Issue by ntromas** [cruizperez/MicrobeAnnotator#45]
Hi!

I am trying to download the full db using Aspera and I got an error at step 9 :

Completed: 392708K bytes transferred in 58 seconds
 (54553K bits/sec), in 14 files, 1 directory.
2022-02-15 13:32:43,211 [INFO]: Merging protein files
Traceback (most recent call last):
  File "/home/nico/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/home/nico/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/home/nico/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 175, in database_duilder
    refseq_prot = refseq.refseq_fasta_downloader(database_directory)
  File "/home/nico/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/refseq_data_downloader.py", line 104, in refseq_fasta_downloader
    rmtree(temp_fasta_files)
  File "/home/nico/miniconda3/envs/microbeannotator/lib/python3.7/shutil.py", line 498, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/nico/miniconda3/envs/microbeannotator/lib/python3.7/shutil.py", line 496, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: 'MicrobeAnnotator_full/temp_refseq_proteins'

The funny part is tat the folder temp_refseq_proteins is empty...

Thanks for your help,

Nico

**Comment by silvtal** [comment]
You could try out [my branch](https://github.com/silvtal/MicrobeAnnotator), which helped me with similar database-building problems. I list the changes I made [here](https://github.com/cruizperez/MicrobeAnnotator/pull/38)

**Comment by justinmaire** [comment]
Hello, 

I'm having exactly the same issue and the database builder stops at step 9, has there been an update to fix it, or is there something else I should do that will fix it?

Thanks!
Justin

**Comment by NataliHB** [comment]
Hi,

I am having the same issue in this step:

2022-10-10 09:22:32,724 [INFO]: Step 9
2022-10-10 09:22:32,724 [INFO]: Downloading protein fasta files using Aspera Connect.
Traceback (most recent call last):
  File "/mnt/iusers01/fatpou01/sees01/mbexrnh4/.conda/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/mnt/iusers01/fatpou01/sees01/mbexrnh4/.conda/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/mnt/iusers01/fatpou01/sees01/mbexrnh4/.conda/envs/microbeannotator/bin/microbeannotator_db_builder", line 175, in database_duilder
    refseq_prot = refseq.refseq_fasta_downloader(database_directory)
  File "/mnt/iusers01/fatpou01/sees01/mbexrnh4/.conda/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/refseq_data_downloader.py", line 61, in refseq_fasta_downloader
    ascp_key = get_aspera_key()
  File "/mnt/iusers01/fatpou01/sees01/mbexrnh4/.conda/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/refseq_data_downloader.py", line 277, in get_aspera_key
    install_folder = Path(path_to_ascp).parents[1]
  File "/mnt/iusers01/fatpou01/sees01/mbexrnh4/.conda/envs/microbeannotator/lib/python3.7/pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "/mnt/iusers01/fatpou01/sees01/mbexrnh4/.conda/envs/microbeannotator/lib/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/mnt/iusers01/fatpou01/sees01/mbexrnh4/.conda/envs/microbeannotator/lib/python3.7/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Does anyone has managed to solve this?

Cheers,
Natali
