### ISSUE TITLE
prokaryote.hal File not found

### ISSUE THREAD

**Issue by mauricebarrett** [cruizperez/MicrobeAnnotator#46]
Hi,

I recently install your tool and I am constructing the necessary database.

I am however running into the below error. 

Thank you for any help in advance.

2022-02-24 12:00:54,073 [INFO]: Finished
2022-02-24 12:00:54,073 [INFO]: Step 2
2022-02-24 12:00:54,073 [INFO]: Formatting KOfam profiles
Traceback (most recent call last):
  File "/Users/maurice/opt/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/Users/maurice/opt/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/Users/maurice/opt/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 97, in database_duilder
    kofam.kofam_formatter(ko_profiles_path)
  File "/Users/maurice/opt/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/kofam_profile_parser.py", line 112, in kofam_formatter
    with open(ko_profiles_path_extr / 'prokaryote.hal', 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/maurice/databases/MicrobeAnnotator_DB/kofam_data/profiles/prokaryote.hal'

**Comment by Sam-J-1** [comment]
Hi,
I'm currently having the same issue. Did you manage to solve it?

**Comment by MAllen91** [comment]
I am also having the same issue an update or resolution?

**Comment by SaitouAsuka** [comment]
It seens like the urls from **kofam_profile_parser.py** (line 71 and line 81) have been removed. I suggest you download the kofam databases manually and extract them. 
Here is the link: https://www.genome.jp/ftp/db/kofam/

**Comment by SaitouAsuka** [comment]
> I am also having the same issue an update or resolution?


It seens like the urls in kofam_profile_parser.py (line 71 and line 81) have been removed. I suggest you download the kofam databases manually and extract them.
Here is the link: https://www.genome.jp/ftp/db/kofam/

**Comment by Sam-J-1** [comment]
Hi,

I resolved it my running the code in ubuntu as its written for linux.

Many thanks,
Sam
________________________________

**Comment by Sam-J-1** [comment]
by*
________________________________
