### ISSUE TITLE
Fatal exception while parsing HMM profile metadata

### ISSUE THREAD

**Issue by galtoledano** [cruizperez/MicrobeAnnotator#53]
Hi, I'm running the following command:
microbeannotator -i ../data/pch.fasta -o pch_light_microbannotator -d ~/MicrobeAnnotator_DB_less -m  blast

and getting this fatal exception at the 'Parsing HMM profile metadata' step.
do you have any idea why that happened? 

2022-05-03 10:37:10,466 [INFO]:  ---- This is MicrobeAnnotator v2.0.4 ----
2022-05-03 10:37:10,466 [INFO]: Validating user inputs
2022-05-03 10:37:10,467 [INFO]: Passed
2022-05-03 10:37:10,467 [INFO]: Processing 1 files. I will run 1 files in parallel with 1 threads per file.
2022-05-03 10:37:10,480 [INFO]: Searching proteins against KOfam profiles
2022-05-03 10:37:10,480 [INFO]: Parsing HMM profile metadata
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/hmmsearch.py", line 57, in hmmer_search
    output=temporal_result)
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/hmmer.py", line 250, in search
    return self._match(hmmsearch, target, opts)
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/hmmer.py", line 267, in _match
    check_call(cmd_match)
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/bin/v3.3.2/hmmsearch_manylinux2010_x86_64', '-o', '/tmp/tmp9m2uxzxxZ8VF22E6JI17RVTRGG1I', '--tblout', '/tmp/tmphx3ra39v/tbl.txt', '--domtblout', '/tmp/tmphx3ra39v/domtbl.txt', '/home/galtol/MicrobeAnnotator_DB_less/kofam_data/profiles/common_1.model', '/home/galtol/lab/genomic_evo/analysis_results/seq_results_dec2021/annotators_check/../data/pch.fasta']' died with <Signals.SIGABRT: 6>.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/galtol/miniconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/home/galtol/miniconda3/envs/microbeannotator/bin/microbeannotator", line 367, in main
    processes=processes, threads=threads)
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/hmmsearch.py", line 192, in hmmsearch_launcher
    hmmer_search, protein_model_list)
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '['/home/galtol/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/bin/v3.3.2/hmmsearch_manylinux2010_x86_64', '-o', '/tmp/tmp9m2uxzxxZ8VF22E6JI17RVTRGG1I', '--tblout', '/tmp/tmphx3ra39v/tbl.txt', '--domtblout', '/tmp/tmphx3ra39v/domtbl.txt', '/home/galtol/MicrobeAnnotator_DB_less/kofam_data/profiles/common_1.model', '/home/galtol/lab/genomic_evo/analysis_results/seq_results_dec2021/annotators_check/../data/pch.fasta']' died with <Signals.SIGABRT: 6>.

Thanks.

**Comment by Sam-J-1** [comment]
Hi,
I'm having the same issue. Did you manage to fix it?

**Comment by galtoledano** [comment]
> 

No, I used a different tool.

**Comment by Sam-J-1** [comment]
I managed to work out what the problem was for me. You need to use a file containing protein sequences for your genome, as the tool does not have a CDS identification function.
