### ISSUE TITLE
sqlite3 error

### ISSUE THREAD

**Issue by PengfanZhang** [cruizperez/MicrobeAnnotator#54]
Hi,

I'm runnining microbeannotator with either light or full version, but I'm stuck with the sqlite3 error with the swissprot database.

```
Traceback (most recent call last):
  File "/netscratch/dep_psl/grp_rgo/pzhang/tools/MicrobeAnnotator/bin/microbeannotator", line 994, in <module>
    main()
  File "/netscratch/dep_psl/grp_rgo/pzhang/tools/MicrobeAnnotator/bin/microbeannotator", line 489, in main
    refdata.microbeannotator_db, "swissprot", significant_hits)
  File "/netscratch/dep_psl/grp_rgo/pzhang/tools/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/sqlite3_search.py", line 135, in search_ids_imported
    cur.execute("SELECT * FROM " + database_table + " WHERE gene_id=?", (gene_id,))
sqlite3.OperationalError: no such table: swissprot
```

I'm wondering how I can fix it?

**Comment by natashagriffin** [comment]
Hi! I just ran into this same error, missing swissprot table and an empty microbeannotator.db file. Did either of you find a solution already? If I figure it out I will update here.

**Comment by ChingHsiangChin** [comment]
Hi,
I am facing a similar error in --light mode at step 12, saying that my database is locked. 

Traceback (most recent call last):
  File "/home/public/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line
    main()
  File "/home/public/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line
    single_step, aspera, keep_temp, bin_path)
  File "/home/public/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line
    sqlite.create_swissprot_table(sql_database, final_sprot_table)
  File "/home/public/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeanno
    process TEXT, interpro TEXT, pfam TEXT, ec_number TEXT)')
sqlite3.OperationalError: database is locked

Any idea how to solve it?
