### ISSUE TITLE
Error while searching proteins against Swissprot

### ISSUE THREAD

**Issue by Aluminio-visto** [cruizperez/MicrobeAnnotator#55]
Hi everyone,
I'm using Microbeannotator to re-annotate some plasmid proteins I've got in a Prokka.faa file. As I built the database with diamond method, I launch microbeannotator with the same method but I keep getting the same error (see below). When I try to run it with sword metod everything goes fine (although pretty slowly), with blast method the program is not able to run the swissprot, refseq or trembl sections.
I'm running on a 132Gb, 36 threads machine with enough disk space. Ubuntu 20.04, Conda with microbeannotator virtual environment. I tried to solve this by downloading a properly functioning diamond binary and using --method_bin, but it doesn't work neither.
Any help would be greatly appreciated. Thank you in advance.

microbeannotator -i ./ref/PROKKA_05122022.faa -d /home/usuario/Databases/microbeannotator/ --method diamond  -o ./microannotb --threads 30

2022-05-20 14:49:34,893 [INFO]:  ---- This is MicrobeAnnotator v2.0.5 ---- 
2022-05-20 14:49:34,893 [INFO]: Validating user inputs
2022-05-20 14:49:34,893 [INFO]: Passed
2022-05-20 14:49:34,893 [INFO]: Processing 1 files. I will run 1 files in parallel with 30 threads per file.
2022-05-20 14:49:34,894 [INFO]: Searching proteins against KOfam profiles
2022-05-20 14:49:34,894 [INFO]: Parsing HMM profile metadata
2022-05-20 14:49:42,431 [INFO]: Filtering and saving results...
2022-05-20 14:49:42,436 [INFO]: Search against KOfam done!
2022-05-20 14:49:42,483 [INFO]: Searching proteins against Swissprot
No such file or directory
Error: Error calling stat on file /home/usuario/Databases/microbeannotator/protein_db/uniprot_sprot.dmnd
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/usuario/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/usuario/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/usuario/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 232, in similarity_search
    blast_filter_slow(method_output_file, filtered_file, id_perc, bitscore, evalue, aln_percent)
  File "/home/usuario/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 138, in blast_filter_slow
    with open(input_tab) as blast_input:
FileNotFoundError: [Errno 2] No such file or directory: 'microannotb/swissprot_results/PROKKA_05122022.faa.step_2.diamond'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/usuario/miniconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/home/usuario/miniconda3/envs/microbeannotator/bin/microbeannotator", line 429, in main
    multiple_arguments=arguments_to_pass), input_proteins)
  File "/home/usuario/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/usuario/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'microannotb/swissprot_results/PROKKA_05122022.faa.step_2.diamond'

**Comment by Nichocolas** [comment]
Hi @Aluminio-visto,

I have the same error, may you have some update on this?

Thanks

**Comment by luciagrami** [comment]
There is a similar issue and apparently the problem is diamond, if you change to method blast it works fine

**Comment by ntorres17** [comment]
Did anyone find a solution? I can run blast perfectly fine but not sword. Is it that the microbeannotator_DB folder ONLY contains either blast OR sword OR diamond? I was under the belief i had installed all 3 but running into issues. 

Thank you in advance for a response!
