### ISSUE TITLE
DB download error

### ISSUE THREAD

**Issue by kalonji08** [cruizperez/MicrobeAnnotator#56]
Hello I'm struggling to download the database here is my error code:

microbeannotator_db_builder -h
Traceback (most recent call last):
  File "/home/kalonjilab/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 18, in <module>
    from microbeannotator.database import conversion_database_creator as convert
  File "/home/kalonjilab/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/conversion_database_creator.py", line 26, in <module>
    import wget
ModuleNotFoundError: No module named 'wget'

**Comment by OSAGSoliman** [comment]
Hello,

inside the same conda environment run:

conda install -c conda-forge python-wget

this fix the same problem in my PC
