### ISSUE TITLE
Error creating the plots in a server probably because X11/user interface required

### ISSUE THREAD

**Issue by matrs** [cruizperez/MicrobeAnnotator#6]
Hello, thanks for this software.
I had this issue in a server, probably related to X11. I solved it adding `matplotlib.use('Agg')` to the two functions that create the plots in `ko_mapper.py`
```
Traceback (most recent call last):
  File "/home/jmaturana/miniconda3/envs/roary/bin/microbeannotator", line 11, in <module>
    sys.exit(main())
  File "/home/jmaturana/miniconda3/envs/roary/bin/microbeannotator.py", line 729, in main
    metabolism_matrix_dropped_relabel, module_colors = ko_mapper.create_output_files(metabolic_annotation, metabolism_matrix, module_information, cluster, prefix)
  File "/home/jmaturana/miniconda3/envs/roary/lib/python3.7/site-packages/independent_scripts/ko_mapper.py", line 567, in create_output_files
    cbar_kws= {'orientation': 'horizontal', 'label': 'Module Completeness (%)'}, dendrogram_ratio=0.1)
  File "/home/jmaturana/miniconda3/envs/roary/lib/python3.7/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/jmaturana/miniconda3/envs/roary/lib/python3.7/site-packages/seaborn/matrix.py", line 1406, in clustermap
    colors_ratio=colors_ratio, cbar_pos=cbar_pos)
  File "/home/jmaturana/miniconda3/envs/roary/lib/python3.7/site-packages/seaborn/matrix.py", line 800, in __init__
    self.fig = plt.figure(figsize=figsize)
  File "/home/jmaturana/miniconda3/envs/roary/lib/python3.7/site-packages/matplotlib/pyplot.py", line 546, in figure
    **kwargs)
  File "/home/jmaturana/miniconda3/envs/roary/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3358, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/jmaturana/miniconda3/envs/roary/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 888, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/home/jmaturana/miniconda3/envs/roary/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:10.0"
```

**Comment by cruizperez** [comment]
Hello! Thanks for spotting this one, we haven't encountered this issue yet so I am glad you caught it. I have included matplotlib.use('Agg') in both functions as well.
