### ISSUE TITLE
ko_mapper.py

### ISSUE THREAD

**Issue by mattoslmp** [cruizperez/MicrobeAnnotator#60]
Dear Carlos Ruiz. I intend use your script ko_mapper.py to generate kegg modules completenss (complete or not complete) using a ko list (Ex: ko_list.txt). I think that your script could give me this information. Can you provide a example of input format of ko_list.txt for ko_mapper.py ?

**Comment by NataliHB** [comment]
Hi,

I'd also appreciate and example of how to do format the input file.

**Comment by Flomauf** [comment]
The input files are simply a list of KO numbers, with one KO per line.

```
K15523
K00254
K09765
K04750
K06978
K01318
...
```

**Comment by javiercnav** [comment]
Hello there, I have a tab file with the first column being a MAG-ID and second being a KO number. I am trying to run ko_mapper.py, and i got the following error:
`./ko_mapper.py -i kos.genomes_copy.tsv --prefix output --cluster "both"
Importing data... Traceback (most recent call last):
  File "./ko_mapper.py", line 623, in <module>
    main()
  File "./ko_mapper.py", line 615, in main
    module_information, metabolism_matrix, module_group_matrix = module_information_importer(input_files)
  File "./ko_mapper.py", line 93, in module_information_importer
    regular_modules = import_module_dict(data_folder / "01.KEGG_Regular_Module_Information.pickle")
  File "./ko_mapper.py", line 83, in import_module_dict
    pickle_in = open(dictionary_location,"rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/01.KEGG_Regular_Module_Information.pickle'`
My guess is that I need to somehow indicate the location of my database. Am I correct? If so, how can I do this?
Thanks a lot
