### ISSUE TITLE
DB builder error at step 11-- assertion error? 

### ISSUE THREAD

**Issue by natashagriffin** [cruizperez/MicrobeAnnotator#62]
Hi there! Thank you for making this awesome annotation tool, I am really excited to try it out on my metatranscriptomes. 

I have been working on installing the database on my space within my university's Linux cluster environment. I had to restart and run some steps individually during steps 1-10 because we are supposed to download files and run jobs on different host machines, but everything seemed to work up until step 11. Can you give me any tips for addressing this error? I found a [past issue ](https://github.com/cruizperez/MicrobeAnnotator/issues/2) that looks similar, but it looks like it was a small program bug that had been fixed. 

Thanks again!!

(microbeannotator) [grifnata@congo microbeannotator]$ microbeannotator_db_builder -d MicrobeAnnotator_DB -m diamond -t 40 --step 11
2022-08-22 12:01:01,503 [INFO]: This is MicrobeAnnotator v2.0.5
2022-08-22 12:01:01,503 [INFO]: I will download and format the databases I use.
2022-08-22 12:01:01,503 [INFO]: Creating database folders
2022-08-22 12:01:01,503 [INFO]: Step 11
Traceback (most recent call last):
  File "/nfs5/Lab/grifnata/conda/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/nfs5/Lab/grifnata/conda/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/nfs5/Lab/grifnata/conda/envs/microbeannotator/bin/microbeannotator_db_builder", line 206, in database_duilder
    viral_list = refseq.search_all_files(temp_gb_dir / "viral")
  File "/nfs5/Lab/grifnata/conda/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/refseq_data_downloader.py", line 293, in search_all_files
    assert(dirpath.is_dir())
AssertionError

**Comment by natashagriffin** [comment]
I figured out this issue-- it seems to be because when running steps individually, any temporary files created during the step are deleted at the end. In this case a temporary file created during step 10 was required for step 11.  I fixed this by re-running step 10 with the --keep flag to avoid deleting the temporary file used in step 11.
