### ISSUE TITLE
During step13 there is an error. please help me

### ISSUE THREAD

**Issue by suppakoko** [cruizperez/MicrobeAnnotator#63]
I executed below command.
During step 13 "Createing InterPro tables" 
there is a error like below 

yjko84@banana:~/analysis_tools/MicrobeAnnotator/bin$ microbeannotator_db_builder -d MicrobeAnnotator_DB -m blast -t 250 --step 13 --bin_path /home/yjko84/analysis_tools/MicrobeAnnotator/bin
2022-08-25 20:25:12,829 [INFO]: This is MicrobeAnnotator v2.0.5
2022-08-25 20:25:12,829 [INFO]: I will download and format the databases I use.
2022-08-25 20:25:12,829 [INFO]: Creating database folders
2022-08-25 20:25:12,829 [INFO]: Step 13
2022-08-25 20:25:12,829 [INFO]: Creating RefSeq to UniProt table
2022-08-25 20:27:31,768 [INFO]: Finished
2022-08-25 20:27:31,781 [INFO]: Creating KO to EC table
100% [..............................................................................] 50126 / 501262022-08-25 20:27:33,031 [INFO]: Finished
2022-08-25 20:27:33,031 [INFO]: Creating InterPro tables
Traceback (most recent call last):
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 2450, in retrfile
    self.ftp.cwd(file)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/ftplib.py", line 638, in cwd
    return self.voidcmd(cmd)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/ftplib.py", line 280, in voidcmd
    return self.voidresp()
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/ftplib.py", line 253, in voidresp
    resp = self.getresp()
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to change directory.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 1573, in ftp_open
    fp, retrlen = fw.retrfile(file, type)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 2452, in retrfile
    raise URLError('ftp error: %r' % reason) from reason
urllib.error.URLError: <urlopen error ftp error: error_perm('550 Failed to change directory.')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yjko84/anaconda3/envs/manno/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/home/yjko84/anaconda3/envs/manno/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/home/yjko84/anaconda3/envs/manno/bin/microbeannotator_db_builder", line 285, in database_duilder
    database_directory, interconversion_database)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/site-packages/microbeannotator/database/conversion_database_creator.py", line 156, in create_interpro_tables
    out=download_output)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 1584, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 1573, in ftp_open
    fp, retrlen = fw.retrfile(file, type)
  File "/home/yjko84/anaconda3/envs/manno/lib/python3.7/urllib/request.py", line 2452, in retrfile
    raise URLError('ftp error: %r' % reason) from reason
urllib.error.URLError: <urlopen error ftp error: URLError("ftp error: error_perm('550 Failed to change directory.')")>

Could you help me ?

**Comment by natashagriffin** [comment]
I just got this exact same error and have yet to figure it out. If I do I will update here! Hopefully someone else has already solved it.

**Comment by suppakoko** [comment]
I solved it. it was so simple.
Just changed the link
ftp://ftp.ebi.ac.uk/pub/databases/interpro/current_release/interpro.xml.gz
in the file $HOME/anaconda3/envs/manno/lib/python3.7/site-packages/microbeannotator/database/conversion_database_creator.py
Thanks

**Comment by natashagriffin** [comment]
Awesome!! Thank you so much for the fix, I had gone completely down the wrong troubleshooting path. 

Did you succeed at running the step afterward? I tried to start step 13 over again but it seems to be stuck at the RefSeq to UniProt table creation step now. :/

**Comment by suppakoko** [comment]
Good luck! @natashagriffin

**Comment by gyeongjunCho** [comment]
I also had the same problem, but after applying @suppakoko's troubleshooting method, it was completely fixed.

thank you.
