### ISSUE TITLE
MicrobeAnnotator running error

### ISSUE THREAD

**Issue by 17863952296** [cruizperez/MicrobeAnnotator#66]
2022-09-14 14:48:57,256 [INFO]:  ---- This is MicrobeAnnotator v2.0.4 ---- 
2022-09-14 14:48:57,256 [INFO]: Validating user inputs
2022-09-14 14:48:57,261 [INFO]: Passed
2022-09-14 14:48:57,261 [INFO]: Processing 1 files. I will run 1 files in parallel with 12 threads per file.
2022-09-14 14:48:57,292 [INFO]: Restarting from last checkpoint
Traceback (most recent call last):
  File "/usr/local/bin/microbeannotator", line 981, in <module>
    main()
  File "/usr/local/bin/microbeannotator", line 299, in main
    with open(process_log_folder / "log.txt", 'r') as logfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/process_log/log.txt'
how to solve it? please,please,please

**Comment by bloomarun** [comment]
What was the output folder that you directed microbeannotator to write results? Do you have read/write permissions to that particular folder?

**Comment by zshivji** [comment]
I am having the same problem (process_log folder is empty) and do have read/write permissions enabled for the folder.

**Comment by susheelbhanu** [comment]
I have the same issue - the restart/checkpoint information files are missing
