### ISSUE TITLE
error indexError: list index out of range - Step 12

### ISSUE THREAD

**Issue by jayramr** [cruizperez/MicrobeAnnotator#67]
Hi,

Error getting after the 12th 

Excecuting the command below 
microbeannotator_db_builder -d /scratch/jr5241/microbeannotator -m diamond -t 1 --no_aspera --step 12 --keep

```
2022-09-19 22:52:54,420 [INFO]: Merging annotations into SQLite database.
2022-09-19 22:52:54,424 [INFO]: Creating RefSeq table
2022-09-19 22:53:18,123 [INFO]: Finished
2022-09-19 22:53:18,147 [INFO]: Creating TrEMBL table
2022-09-20 01:34:25,320 [INFO]: Finished
2022-09-20 01:34:25,445 [INFO]: Parsing RefSeq KO numbers
2022-09-20 01:37:48,175 [INFO]: Finished
2022-09-20 01:37:48,175 [INFO]: Creating RefSeq table
Traceback (most recent call last):
  File "/scratch/jr5241/conda-envs/microbeannotar/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/scratch/jr5241/conda-envs/microbeannotar/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/scratch/jr5241/conda-envs/microbeannotar/bin/microbeannotator_db_builder", line 256, in database_duilder
    sqlite.create_refseq_table(sql_database, final_refseq_table)
  File "/scratch/jr5241/conda-envs/microbeannotar/lib/python3.7/site-packages/microbeannotator/database/sqlite3_database_builder.py", line 177, in create_refseq_table
    records.append((line[0], line[1], line[2],
IndexError: list index out of range
```

Please advise .

**Comment by jayramr** [comment]
@suppakoko could you advise about this error?
