### ISSUE TITLE
why error ? i DB install --light 

### ISSUE THREAD

**Issue by kdyoung100** [cruizperez/MicrobeAnnotator#73]
microbeannotator -i /home/kdyoung/1158_Efaecium.fasta -d /data1/tools/MicrobeAnnotator_DB/ -o /home/kdyoung/1158_Efaecium_microbeannotator/ -m blast -t 16 
2022-12-02 10:16:36,244 [INFO]:  ---- This is MicrobeAnnotator v2.0.5 ---- 
2022-12-02 10:16:36,244 [INFO]: Validating user inputs
2022-12-02 10:16:36,245 [INFO]: Passed
2022-12-02 10:16:36,245 [INFO]: Processing 1 files. I will run 1 files in parallel with 16 threads per file.
2022-12-02 10:16:36,252 [INFO]: Searching proteins against KOfam profiles
2022-12-02 10:16:36,252 [INFO]: Parsing HMM profile metadata
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)

Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)Fatal exception (source file p7_pipeline.c, line 697):

Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/hmmsearch.py", line 57, in hmmer_search
    output=temporal_result)
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/hmmer.py", line 250, in search
    return self._match(hmmsearch, target, opts)
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/hmmer.py", line 267, in _match
    check_call(cmd_match)
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/bin/v3.3.2/hmmsearch_manylinux2010_x86_64', '-o', '/tmp/tmpgufeiwtk2CN2VKSY4SF30Q90HTOD', '--tblout', '/tmp/tmp66s4x5b2/tbl.txt', '--domtblout', '/tmp/tmp66s4x5b2/domtbl.txt', '/data1/tools/MicrobeAnnotator_DB/kofam_data/profiles/independent_2.model', '/home/kdyoung/1158_Efaecium.fasta']' died with <Signals.SIGABRT: 6>.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data1/tools/anaconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/data1/tools/anaconda3/envs/microbeannotator/bin/microbeannotator", line 367, in main
    processes=processes, threads=threads)
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/hmmsearch.py", line 192, in hmmsearch_launcher
    hmmer_search, protein_model_list)
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '['/data1/tools/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/bin/v3.3.2/hmmsearch_manylinux2010_x86_64', '-o', '/tmp/tmpgufeiwtk2CN2VKSY4SF30Q90HTOD', '--tblout', '/tmp/tmp66s4x5b2/tbl.txt', '--domtblout', '/tmp/tmp66s4x5b2/domtbl.txt', '/data1/tools/MicrobeAnnotator_DB/kofam_data/profiles/independent_2.model', '/home/kdyoung/1158_Efaecium.fasta']' died with <Signals.SIGABRT: 6>.

**Comment by Sam-J-1** [comment]
Hi,
I'm having the same issue. Did you manage to fix it?
