### ISSUE TITLE
Microbeannotator database download error..

### ISSUE THREAD

**Issue by sowptika** [cruizperez/MicrobeAnnotator#74]
Traceback (most recent call last):
  File "/home/adminuser/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 18, in <module>
    from microbeannotator.database import conversion_database_creator as convert
  File "/home/adminuser/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/conversion_database_creator.py", line 26, in <module>
    import wget
ModuleNotFoundError: No module named 'wget'

**Hello Authors,
I am facing the above error while creating the database. I am trying to install the Microbeannotator in server wherein I cannot download the aspera connect so using the flag --no_aspera. I checked for the presence of wget in my server and it is present in /usr/bin/wget. So not able to resolve this error.
Please help me to solve this issue.**

Thanking You
Sincerely,
Sowptika Pal

**Comment by DininduSenanayake** [comment]
@sowptika Looks like your python environment is missing [wget](https://pypi.org/project/wget/) . Can you install  it with `pip install wget`  which hopefully resolves the `ModuleNotFoundError: No module named 'wget'`
