### ISSUE TITLE
database installation error

### ISSUE THREAD

**Issue by saras224** [cruizperez/MicrobeAnnotator#75]
Hi @lmrodriguezr 
I am getting this error while trying to download the MicrobeAnnotator database:
(microbeannotator) microbeannotator_db_builder -d MicrobeAnnotator_DB -m [blast,diamond,sword] -t 40
2023-02-20 14:16:22,892 [INFO]: This is MicrobeAnnotator v2.0.5
2023-02-20 14:16:22,893 [INFO]: I will download and format the databases I use.
2023-02-20 14:16:22,893 [INFO]: Creating database folders
2023-02-20 14:16:22,894 [INFO]: Step 1
2023-02-20 14:16:22,894 [INFO]: Downloading KOfam data
100% [............................................................................] 823196 / 823196gzip: MicrobeAnnotator_DB/kofam_data/ko_list already exists; do you wish to overwrite (y or n)? n
	not overwritten
100% [....................................................................] 1403716982 / 14037169822023-02-20 15:41:15,994 [INFO]: Extracting profiles
2023-02-20 15:43:06,573 [INFO]: Finished
2023-02-20 15:43:06,574 [INFO]: Step 2
2023-02-20 15:43:06,574 [INFO]: Formatting KOfam profiles
2023-02-20 15:44:00,315 [INFO]: Finished
2023-02-20 15:44:00,319 [INFO]: Step 3
2023-02-20 15:44:04,119 [INFO]: Downloading SwissProt Fasta files
100% [........................................................................] 91432446 / 914324462023-02-20 15:49:20,717 [INFO]: Finished
2023-02-20 15:49:20,718 [INFO]: Step 4
2023-02-20 15:49:20,720 [INFO]: Downloading Swissprot .dat files
100% [......................................................................] 644647457 / 6446474572023-02-20 16:17:21,559 [INFO]: Finished
2023-02-20 16:17:21,559 [INFO]: Step 5
2023-02-20 16:17:21,559 [INFO]: Parsing MicrobeAnnotator_DB/temp_swissprot_dat_files/uniprot_sprot.dat.gz and storing in MicrobeAnnotator_DB/uniprot_swissprot.table
2023-02-20 16:18:58,543 [INFO]: Finished
2023-02-20 16:18:58,543 [INFO]: Step 6
2023-02-20 16:19:01,685 [INFO]: Downloading TrEMBL Fasta files

24% [................                                                  ] 13970448384 / 57043853550Traceback (most recent call last):
  File "/home/rsharma/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/home/rsharma/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/home/rsharma/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 141, in database_duilder
    trembl_fasta = uniprot.trembl_fasta_downloader(database_directory)
  File "/home/rsharma/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/uniprot_data_downloader.py", line 148, in trembl_fasta_downloader
    wget.download(fasta_url, out=str(output_fasta))
  File "/home/rsharma/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/home/rsharma/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "/home/rsharma/anaconda3/envs/microbeannotator/lib/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
  File "/home/rsharma/anaconda3/envs/microbeannotator/lib/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
  File "/home/rsharma/anaconda3/envs/microbeannotator/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

Kindly help me resolve the error.

Thanks in Advance!! :)

**Comment by lmrodriguezr** [comment]
@cruizperez Hi Carlos! Any ideas? Looks to me like a network issue, but I'm not familiar enough with the code.
