### ISSUE TITLE
FTP error while downloading database ftplib.error_perm: 550 Failed to change directory.

### ISSUE THREAD

**Issue by saras224** [cruizperez/MicrobeAnnotator#78]
Hi @lmrodriguezr @cruizperez 
I got en error while trying to download Microbeannotator database.
2023-04-03 16:07:38,044 [INFO]: This is MicrobeAnnotator v2.0.5
2023-04-03 16:07:38,044 [INFO]: I will download and format the databases I use.
2023-04-03 16:07:38,044 [INFO]: Creating database folders
2023-04-03 16:07:38,044 [INFO]: Step 13
2023-04-03 16:07:38,045 [INFO]: Creating RefSeq to UniProt table
2023-04-03 16:07:46,276 [INFO]: Finished
2023-04-03 16:07:46,309 [INFO]: Creating KO to EC table
100% [..............................................................................] 50126 / 501262023-04-03 16:07:48,326 [INFO]: Finished
2023-04-03 16:07:48,327 [INFO]: Creating InterPro tables
Traceback (most recent call last):
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 2450, in retrfile
    self.ftp.cwd(file)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/ftplib.py", line 638, in cwd
    return self.voidcmd(cmd)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/ftplib.py", line 280, in voidcmd
    return self.voidresp()
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/ftplib.py", line 253, in voidresp
    resp = self.getresp()
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to change directory.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 1573, in ftp_open
    fp, retrlen = fw.retrfile(file, type)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 2452, in retrfile
    raise URLError('ftp error: %r' % reason) from reason
urllib.error.URLError: <urlopen error ftp error: error_perm('550 Failed to change directory.')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/home/rakesh/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/home/rakesh/anaconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 285, in database_duilder
    database_directory, interconversion_database)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/conversion_database_creator.py", line 156, in create_interpro_tables
    out=download_output)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 1584, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 1573, in ftp_open
    fp, retrlen = fw.retrfile(file, type)
  File "/home/rakesh/anaconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 2452, in retrfile
    raise URLError('ftp error: %r' % reason) from reason
urllib.error.URLError: <urlopen error ftp error: URLError("ftp error: error_perm('550 Failed to change directory.')")>

Please help me resolve it!
Thanks in Advance!!

**Comment by sudeep71** [comment]
Running into the same error? Any way to resolve it? Looks like a file permission?
