### ISSUE TITLE
Error，‘Connection refuse’d and ‘550 Failed to change directory’ during step 13, please help me

### ISSUE THREAD

**Issue by XingshengYang** [cruizperez/MicrobeAnnotator#79]
Hi all,
I meet error “550 Failed to change directory” in step 13 as issue # 63 mentioned.
I changed the link “ftp://ftp.ebi.ac.uk/pub/databases/interpro/current_release/interpro.xml.gz” according to the answer.
But the connection was refused. Please give me some tips to resolve it.
Thanks!!!

2023-04-17 07:49:12,400 [INFO]: This is MicrobeAnnotator v2.0.4
2023-04-17 07:49:12,401 [INFO]: I will download and format the databases I use.
2023-04-17 07:49:12,401 [INFO]: Creating database folders
2023-04-17 07:49:12,401 [INFO]: Step 13
2023-04-17 07:49:12,401 [INFO]: Creating RefSeq to UniProt table
2023-04-17 07:49:16,595 [INFO]: Finished
2023-04-17 07:49:16,618 [INFO]: Creating KO to EC table
100% [..............................................................................] 50126 / 501262023-04-17 07:49:18,063 [INFO]: Finished
2023-04-17 07:49:18,065 [INFO]: Creating InterPro tables
Traceback (most recent call last):
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 1566, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 1588, in connect_ftp
    persistent=False)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 2408, in __init__
    self.init()
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 2417, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/ftplib.py", line 154, in connect
    source_address=self.source_address)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/softwares/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 445, in <module>
    main()
  File "/data/softwares/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 437, in main
    single_step, aspera, keep_temp, bin_path)
  File "/data/softwares/miniconda3/envs/microbeannotator/bin/microbeannotator_db_builder", line 285, in database_duilder
    database_directory, interconversion_database)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/database/conversion_database_creator.py", line 157, in create_interpro_tables
    wget.download("ftp://ftp.ebi.ac.uk/pub/databases/interpro/current_release/interpro.xml.gz", out=download_output)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 1584, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 1566, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 1588, in connect_ftp
    persistent=False)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 2408, in __init__
    self.init()
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/urllib/request.py", line 2417, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/ftplib.py", line 154, in connect
    source_address=self.source_address)
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/data/softwares/miniconda3/envs/microbeannotator/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
urllib.error.URLError: <urlopen error ftp error: ConnectionRefusedError(111, 'Connection refused')>

**Comment by xuechunxu** [comment]
I got the same error. How to fix it?

**Comment by volcanihpc** [comment]
The URL in _.../database/conversion_database_creator.py_  has changed.
Edit line 155, and put this URL instead:
[](https://ftp.ebi.ac.uk/pub/databases/interpro/current_release/interpro.xml.gz)
