### ISSUE TITLE
Error with HMM

### ISSUE THREAD

**Issue by mscarbor** [cruizperez/MicrobeAnnotator#82]
Greetings! I'm excited to test out MicrobeAnnotator. After getting DBs installed, my first test on annotating a genome (a metagenomic bin draft genome) yielded the following output:

Starting sbatch script myscript.sh at:Sat Jul  1 07:04:53 EDT 2023
  running host:    node304
  assigned nodes:  node304
  partition used:  bigmem
  jobid:           11015109
2023-07-01 07:04:58,486 [INFO]:  ---- This is MicrobeAnnotator v2.0.5 ---- 
2023-07-01 07:04:58,487 [INFO]: Validating user inputs
2023-07-01 07:04:58,488 [INFO]: Passed
2023-07-01 07:04:58,488 [INFO]: Processing 1 files. I will run 1 files in parallel with 32 threads per file.
2023-07-01 07:04:58,514 [INFO]: Searching proteins against KOfam profiles
2023-07-01 07:04:58,514 [INFO]: Parsing HMM profile metadata
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)

Fatal exception (source file p7_pipeline.c, line 697):
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)

Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Fatal exception (source file p7_pipeline.c, line 697):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/hmmsearch.py", line 57, in hmmer_search
    output=temporal_result)
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/hmmer.py", line 250, in search
    return self._match(hmmsearch, target, opts)
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/hmmer.py", line 267, in _match
    check_call(cmd_match)
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/bin/v3.3.2/hmmsearch_manylinux2010_x86_64', '-o', '/tmp/tmpv8m9ya3_DPN8S767RNI60NXKTSMG', '--tblout', '/tmp/tmp_0ls2099/tbl.txt', '--domtblout', '/tmp/tmp_0ls2099/domtbl.txt', '/users/m/s/mscarbor/MicrobeAnnotator_DB/kofam_data/profiles/common_6.model', '/gpfs1/home/m/s/mscarbor/MaxBin_Polished/MaxBin_Output_IlluminaMapping_Obj1J1.001.fasta']' died with <Signals.SIGABRT: 6>.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/bin/microbeannotator", line 367, in main
    processes=processes, threads=threads)
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/hmmsearch.py", line 192, in hmmsearch_launcher
    hmmer_search, protein_model_list)
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '['/users/m/s/mscarbor/anaconda3/envs/microbeannotator/lib/python3.7/site-packages/hmmer/bin/v3.3.2/hmmsearch_manylinux2010_x86_64', '-o', '/tmp/tmpv8m9ya3_DPN8S767RNI60NXKTSMG', '--tblout', '/tmp/tmp_0ls2099/tbl.txt', '--domtblout', '/tmp/tmp_0ls2099/domtbl.txt', '/users/m/s/mscarbor/MicrobeAnnotator_DB/kofam_data/profiles/common_6.model', '/gpfs1/home/m/s/mscarbor/MaxBin_Polished/MaxBin_Output_IlluminaMapping_Obj1J1.001.fasta']' died with <Signals.SIGABRT: 6>.

---

I'm at a bit of a loss here. Any guidance would be greatly appreciated. 

Thanks!

Matt

**Comment by mscarbor** [comment]
Nevermind! Need ORFs with protein sequences, not DNA sequences. Will preprocess.
