### ISSUE TITLE
Trembl file not formated correctly 

### ISSUE THREAD

**Issue by Louis-MG** [cruizperez/MicrobeAnnotator#91]
Hello, I got this error:

```python
Error: Error detecting input file format. First line seems to be blank.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/guelou01/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/guelou01/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/guelou01/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 232, in similarity_search
    blast_filter_slow(method_output_file, filtered_file, id_perc, bitscore, evalue, aln_percent)
  File "/home/guelou01/miniconda3/envs/microbeannotator/lib/python3.7/site-packages/microbeannotator/pipeline/protein_search.py", line 138, in blast_filter_slow
    with open(input_tab) as blast_input:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/projects_tn03/KMER_analysis/DATA/AcneData/annotation_unitigs/trembl_results/case_unitigs_1000.fasta.step_4.diamond'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guelou01/miniconda3/envs/microbeannotator/bin/microbeannotator", line 981, in <module>
    main()
  File "/home/guelou01/miniconda3/envs/microbeannotator/bin/microbeannotator", line 755, in main
    multiple_arguments=arguments_to_pass), input_proteins)
  File "/home/guelou01/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/guelou01/miniconda3/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/projects_tn03/KMER_analysis/DATA/AcneData/annotation_unitigs/trembl_results/case_unitigs_1000.fasta.step_4.diamond'
```
The trembl table I found in my database seems fine..

UPDATE:  I rebuilt the database, ths is the result, notice the Trembl part:
```
2024-01-20 06:06:11,918 [INFO]: KO profiles:    MicrobeAnnotator_DB/kofam_data/profiles
2024-01-20 06:06:11,918 [INFO]: KO profile metadata:    MicrobeAnnotator_DB/kofam_data/ko_list
2024-01-20 06:06:11,918 [INFO]: Swissprot Fasta:        MicrobeAnnotator_DB/protein_db/uniprot_sprot.fasta.gz
2024-01-20 06:06:11,918 [INFO]: TrEMBL Fasta:   None
2024-01-20 06:06:11,918 [INFO]: RefSeq Fasta:   MicrobeAnnotator_DB/protein_db/refseq_protein.fasta
2024-01-20 06:06:11,919 [INFO]: SQLite database:        MicrobeAnnotator_DB/microbeannotator.db
2024-01-20 06:06:11,919 [INFO]: Conversion database:    MicrobeAnnotator_DB/conversion.db
2024-01-20 06:06:11,919 [INFO]: KO-to-EC table: MicrobeAnnotator_DB/KO_to_EC_identifiers.txt.gz
2024-01-20 06:06:11,919 [INFO]: InterPro table: MicrobeAnnotator_DB/interpro_metadata.xml.gz
```

**Comment by Louis-MG** [comment]
My input was not formated correctly, once changed it went fine. My bad !
